using System.Globalization;
using System.Resources;
using System.Text;
using Aigamo.ResXGenerator.Extensions;
using Aigamo.ResXGenerator.Models;
using Microsoft.CodeAnalysis;

namespace Aigamo.ResXGenerator.Tools;

public class StringBuilderGeneratorHelper
{
	private string ContainerClassName { get; set; }
	private string Indent { get; set; } = "\t";
	private StringBuilder Builder { get; } = new();

	public static string FunctionNamePostFix(IReadOnlyList<ComboItem>? definedLanguages) => string.Join("_", definedLanguages?.Select(x => x.LCID) ?? []);

	public GeneratedOutput GetOutput(string fileName, IntegrityValidator validator) => new(fileName, Builder.ToString(), validator.ErrorsAndWarnings);

	public StringBuilderGeneratorHelper() => ContainerClassName = "Helpers";

	public StringBuilderGeneratorHelper(GenFileOptions options) => ContainerClassName = options.ClassName;

	public void Append(string line) => Builder.Append(line);
	public void AppendLineLF(string line) => Builder.AppendLineLF(line);
	public void AppendFormat(string format, params object[] args) => Builder.AppendFormat(format, args);
	public string AppendLanguages(IReadOnlyList<ComboItem> languages)
	{
		var postFix = FunctionNamePostFix(languages);
		Builder.Append(postFix);
		return postFix;
	}

	public void AppendHeader(string @namespace)
	{
		Builder.AppendLineLF(Constants.AutoGeneratedHeader);
		Builder.AppendLineLF("#nullable enable");
		Builder.Append("namespace ");
		Builder.Append(@namespace);
		Builder.AppendLineLF(";");
	}

	public void AppendInnerClass(GenFileOptions options, IntegrityValidator validator)
	{
		if (options.InnerClassVisibility == InnerClassVisibility.NotGenerated) return;

		ContainerClassName = string.IsNullOrEmpty(options.InnerClassName) ? "Resources" : options.InnerClassName;
		if (!string.IsNullOrEmpty(options.InnerClassInstanceName))
		{
			validator.ValidateInconsistentModificator(options);

			Builder.Append(Indent);
			Builder.Append("public ");
			Builder.Append(ContainerClassName);
			Builder.Append(" ");
			Builder.Append(options.InnerClassInstanceName);
			Builder.AppendLineLF(" { get; } = new();");
			Builder.AppendLineLF();
		}

		Builder.Append(Indent);
		Builder.Append(GetInnerClassVisibility(options));
		Builder.Append(options.StaticClass ? " static" : string.Empty);
		Builder.Append(options.PartialClass ? " partial class " : " class ");

		Builder.AppendLineLF(ContainerClassName);
		Builder.Append(Indent);
		Builder.AppendLineLF("{");

		Indent += "\t";
	}

	public void AppendClassHeader(GenFileOptions options)
	{
		Builder.Append(options.PublicClass ? "public" : "internal");
		Builder.Append(options.StaticClass ? " static" : string.Empty);
		Builder.Append(options.PartialClass ? " partial class " : " class ");
		Builder.AppendLineLF(options.ClassName);
		Builder.AppendLineLF("{");
	}

	public void AppendClassFooter(GenFileOptions options)
	{
		if (options.InnerClassVisibility != InnerClassVisibility.NotGenerated)
			Builder.AppendLineLF("\t}");

		Builder.AppendLineLF("}");
	}

	internal (bool valid, bool resourceAccessByName, TypeNameParser.ParsedTypeName? typeName) GenerateMember(FallBackItem fallbackItem, GenFileOptions options, IntegrityValidator validator)
	{
		string memberName;
		bool resourceAccessByName;

		if (RegexDefinitions.ValidMemberNamePattern.IsMatch(fallbackItem.Key))
		{
			memberName = fallbackItem.Key;
			resourceAccessByName = true;
		}
		else
		{
			memberName = RegexDefinitions.InvalidMemberNameSymbols.Replace(fallbackItem.Key, "_");
			resourceAccessByName = false;
		}


		if (!validator.ValidateMember(fallbackItem, options, ContainerClassName)) return (false, resourceAccessByName, null);

		var typeNameResult = validator.ValidateTypeName(fallbackItem, options);
		if (!typeNameResult.valid) return (false, resourceAccessByName, null);

		switch (typeNameResult.typeName)
		{
			case null:
			case { FullName: "System.String"}:
				GenerateValidatedMemberAsString(fallbackItem, options, memberName);
				break;
			case { FullName: "System.Resources.ResXFileRef" }:
				// ReXFileRef indicates that the string is of the form "<file path>;<type name>[;<encoding]", meaning that the
				// resource compiler actually compiles the contents of the file for the resource. The type used to cast the
				// resource is specified after the first semicolon. However the file name could contain a semicolon and in that
				// case is specified in quotes.

				var resxFileRefType = validator.ValidateResXFileRefValue(fallbackItem, options);
				if (!resxFileRefType.valid) return (false, resourceAccessByName, null);

				GenerateValidatedMemberAsAnyType(fallbackItem, options, memberName, resxFileRefType.typeName!);

				return (true, resourceAccessByName, resxFileRefType.typeName);

			default:
				GenerateValidatedMemberAsAnyType(fallbackItem, options, memberName, typeNameResult.typeName);

				break;
		};

		return (true, resourceAccessByName, typeNameResult.typeName);
	}

	private void GenerateValidatedMemberAsString(FallBackItem fallbackItem, GenFileOptions options, string memberName)
	{
		Builder.AppendLineLF();

		Builder.Append(Indent);
		Builder.AppendLineLF("/// <summary>");

		Builder.Append(Indent);
		Builder.Append("/// Looks up a localized string similar to ");
		Builder.Append(fallbackItem.Value.ToXmlCommentSafe(Indent));
		Builder.AppendLineLF(".");

		Builder.Append(Indent);
		Builder.AppendLineLF("/// </summary>");

		Builder.Append(Indent);
		Builder.Append("public ");
		Builder.Append(options.StaticMembers ? "static " : string.Empty);
		Builder.Append("string");
		Builder.Append(options.NullForgivingOperators ? null : "?");
		Builder.Append(" ");
		Builder.Append(memberName);
	}

	private void GenerateValidatedMemberAsAnyType(FallBackItem fallbackItem, GenFileOptions options, string memberName, TypeNameParser.ParsedTypeName typeName)
	{
		Builder.AppendLineLF();

		Builder.Append(Indent);
		Builder.AppendLineLF("/// <summary>");

		Builder.Append(Indent);
		Builder.Append("/// Looks up a localized resource of type ");
		Builder.Append(typeName.FullName.ToXmlCommentSafe(Indent));
		Builder.AppendLineLF(".");

		Builder.Append(Indent);
		Builder.AppendLineLF("/// </summary>");

		Builder.Append(Indent);
		Builder.Append("public ");
		Builder.Append(options.StaticMembers ? "static " : string.Empty);
		Builder.Append("string");
		Builder.Append(options.NullForgivingOperators ? null : "?");
		Builder.Append(" ");
		Builder.Append(memberName);
	}

	public void AppendResourceManagerUsings()
	{
		Builder.Append("using ");
		Builder.Append(Constants.SystemGlobalization);
		Builder.AppendLineLF(";");

		Builder.Append("using ");
		Builder.Append(Constants.SystemResources);
		Builder.AppendLineLF(";");

		Builder.AppendLineLF();
	}

	public void AppendCodeUsings()
	{
		Builder.AppendLineLF("using static Aigamo.ResXGenerator.Helpers;");
		Builder.AppendLineLF();
	}

	public void GenerateResourceManagerMembers(GenFileOptions options)
	{
		Builder.Append(Indent);
		Builder.Append("private static ");
		Builder.Append(nameof(ResourceManager));
		Builder.Append("? ");
		Builder.Append(Constants.SResourceManagerVariable);
		Builder.AppendLineLF(";");

		Builder.Append(Indent);
		Builder.Append("public static ");
		Builder.Append(nameof(ResourceManager));
		Builder.Append(" ");
		Builder.Append(Constants.ResourceManagerVariable);
		Builder.Append(" => ");
		Builder.Append(Constants.SResourceManagerVariable);
		Builder.Append(" ??= new ");
		Builder.Append(nameof(ResourceManager));
		Builder.Append("(\"");
		Builder.Append(options.EmbeddedFilename);
		Builder.Append("\", typeof(");
		Builder.Append(ContainerClassName);
		Builder.AppendLineLF(").Assembly);");

		Builder.Append(Indent);
		Builder.Append("public ");
		Builder.Append(options.StaticMembers ? "static " : string.Empty);
		Builder.Append(nameof(CultureInfo));
		Builder.Append("? ");
		Builder.Append(Constants.CultureInfoVariable);
		Builder.AppendLineLF(" { get; set; }");
	}

	private static string GetInnerClassVisibility(GenFileOptions options)
	{
		if (options.InnerClassVisibility == InnerClassVisibility.SameAsOuter)
			return options.PublicClass ? "public" : "internal";

		return options.InnerClassVisibility.ToString().ToLowerInvariant();
	}
}
