using Aigamo.ResXGenerator.Generators;
using Aigamo.ResXGenerator.Tools;
using FluentAssertions;
using Xunit;

namespace Aigamo.ResXGenerator.Tests;

public class CodeGenTests
{
	private static void Generate(
		IResXGenerator generator,
		bool publicClass = true,
		bool staticClass = true,
		bool partial = false,
		bool nullForgivingOperators = false,
		bool staticMembers = true
	)
	{
		var expected =
			$$"""
			// ------------------------------------------------------------------------------
			//	<auto-generated>
			//		This code was generated by a tool.
			//
			//		Changes to this file may cause incorrect behavior and will be lost if
			//		the code is regenerated.
			//	</auto-generated>
			// ------------------------------------------------------------------------------
			#nullable enable
			namespace Resources;
			using static Aigamo.ResXGenerator.Helpers;

			{{(publicClass ? "public" : "internal")}}{{(partial ? " partial" : string.Empty)}}{{(staticClass ? " static" : string.Empty)}} class ActivityEntrySortRuleNames
			{

				/// <summary>
				/// Looks up a localized string similar to Oldest.
				/// </summary>
				public{{(staticMembers ? " static" : string.Empty)}} string{{(nullForgivingOperators ? string.Empty : "?")}} CreateDate => GetString_1030_6("Oldest", "OldestDaDK", "OldestDa");

				/// <summary>
				/// Looks up a localized string similar to Newest.
				/// </summary>
				public{{(staticMembers ? " static" : string.Empty)}} string{{(nullForgivingOperators ? string.Empty : "?")}} CreateDateDescending => GetString_1030_6("Newest", "NewestDaDK", "NewestDa");
			}

			""";

		var result = generator.Generate(
			new GenFileOptions
			{
				LocalNamespace = "VocaDb.Web.App_GlobalResources",
				EmbeddedFilename = "VocaDb.Web.App_GlobalResources.ActivityEntrySortRuleNames",
				CustomToolNamespace = "Resources",
				ClassName = "ActivityEntrySortRuleNames",
				GroupedFile = new GroupedAdditionalFile(
					mainFile: new AdditionalTextWithHash(new AdditionalTextStub(string.Empty, CodeResXTestsHelpers.GetText()), Guid.NewGuid()),
					subFiles:
					[
						new AdditionalTextWithHash(new AdditionalTextStub("test.da.rex", CodeResXTestsHelpers.GetText("Da")), Guid.NewGuid()),
						new AdditionalTextWithHash(new AdditionalTextStub("test.da-dk.rex", CodeResXTestsHelpers.GetText("DaDK")), Guid.NewGuid())
					]
				),
				PublicClass = publicClass,
				GenerateCode = true,
				NullForgivingOperators = nullForgivingOperators,
				StaticClass = staticClass,
				PartialClass = partial,
				StaticMembers = staticMembers
			});
		result.ErrorsAndWarnings.Should().BeNullOrEmpty();
		result.SourceCode.ReplaceLineEndings().Should().Be(expected.ReplaceLineEndings());
	}


	[Fact]
	public void Generate_StringBuilder_Public()
	{
		var generator = new CodeGenerator();
		Generate(generator);
		Generate(generator, nullForgivingOperators: true);
	}
}
