using Aigamo.ResXGenerator.Generators;
using Aigamo.ResXGenerator.Tools;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using Xunit;

namespace Aigamo.ResXGenerator.Tests;

public class GeneratorTests
{
	private static void Generate(
		IResXGenerator generator,
		bool publicClass = true,
		bool staticClass = true,
		bool partial = false,
		bool nullForgivingOperators = false,
		bool staticMembers = true
	)
	{
		var expected =
			$$"""
			// ------------------------------------------------------------------------------
			//	<auto-generated>
			//		This code was generated by a tool.
			//
			//		Changes to this file may cause incorrect behavior and will be lost if
			//		the code is regenerated.
			//	</auto-generated>
			// ------------------------------------------------------------------------------
			#nullable enable
			namespace Resources;
			using System.Globalization;
			using System.Resources;

			{{(publicClass ? "public" : "internal")}}{{(staticClass ? " static" : string.Empty)}}{{(partial ? " partial" : string.Empty)}} class ActivityEntrySortRuleNames
			{
				private static ResourceManager? s_resourceManager;
				public static ResourceManager ResourceManager => s_resourceManager ??= new ResourceManager("VocaDb.Web.App_GlobalResources.ActivityEntrySortRuleNames", typeof(ActivityEntrySortRuleNames).Assembly);
				public{{(staticMembers ? " static" : string.Empty)}} CultureInfo? CultureInfo { get; set; }

				/// <summary>
				/// Looks up a localized string similar to Oldest.
				/// </summary>
				public{{(staticMembers ? " static" : string.Empty)}} string{{(nullForgivingOperators ? string.Empty : "?")}} CreateDate => ResourceManager.GetString(nameof(CreateDate), CultureInfo){{(nullForgivingOperators ? "!" : string.Empty)}};

				/// <summary>
				/// Looks up a localized string similar to Newest.
				/// </summary>
				public{{(staticMembers ? " static" : string.Empty)}} string{{(nullForgivingOperators ? string.Empty : "?")}} CreateDateDescending => ResourceManager.GetString(nameof(CreateDateDescending), CultureInfo){{(nullForgivingOperators ? "!" : string.Empty)}};
			}

			""";

		var result = generator.Generate(
			options: new GenFileOptions
			{
				LocalNamespace = "VocaDb.Web.App_GlobalResources",
				EmbeddedFilename = "VocaDb.Web.App_GlobalResources.ActivityEntrySortRuleNames",
				CustomToolNamespace = "Resources",
				ClassName = "ActivityEntrySortRuleNames",
				GroupedFile = new GroupedAdditionalFile(
					mainFile: new AdditionalTextWithHash(new AdditionalTextStub("", CodeResXTestsHelpers.GetText()), Guid.NewGuid()),
					subFiles: []
				),
				PublicClass = publicClass,
				NullForgivingOperators = nullForgivingOperators,
				StaticClass = staticClass,
				PartialClass = partial,
				StaticMembers = staticMembers
			}
		);
		result.ErrorsAndWarnings.Should().BeNullOrEmpty();
		result.SourceCode.ReplaceLineEndings().Should().Be(expected.ReplaceLineEndings());
	}

	private static void GenerateInner(
		IResXGenerator generator,
		bool publicClass = true,
		bool staticClass = false,
		bool partial = false,
		bool nullForgivingOperators = false,
		bool staticMembers = true,
		string innerClassName = "inner",
		InnerClassVisibility innerClassVisibility = InnerClassVisibility.SameAsOuter,
		string innerClassInstanceName = ""
	)
	{
		var expected =
			$$"""
			 // ------------------------------------------------------------------------------
			 //	<auto-generated>
			 //		This code was generated by a tool.
			 //
			 //		Changes to this file may cause incorrect behavior and will be lost if
			 //		the code is regenerated.
			 //	</auto-generated>
			 // ------------------------------------------------------------------------------
			 #nullable enable
			 namespace Resources;
			 using System.Globalization;
			 using System.Resources;

			 {{(publicClass ? "public" : "internal")}}{{(partial ? " partial" : string.Empty)}}{{(staticClass ? " static" : string.Empty)}} class ActivityEntrySortRuleNames
			 {
			 
			 """;

		if (!string.IsNullOrEmpty(innerClassInstanceName))
			expected += $$"""
							public {{innerClassName}} {{innerClassInstanceName}} { get; } = new();


						""";
		expected +=
			$$"""
					{{(publicClass ? "public" : "internal")}}{{(partial ? " partial" : string.Empty)}}{{(staticClass ? " static" : string.Empty)}} class {{innerClassName}}
					{
						private static ResourceManager? s_resourceManager;
						public static ResourceManager ResourceManager => s_resourceManager ??= new ResourceManager("VocaDb.Web.App_GlobalResources.ActivityEntrySortRuleNames", typeof({{innerClassName}}).Assembly);
						public{{(staticMembers ? " static" : string.Empty)}} CultureInfo? CultureInfo { get; set; }

						/// <summary>
						/// Looks up a localized string similar to Oldest.
						/// </summary>
						public{{(staticMembers ? " static" : string.Empty)}} string{{(nullForgivingOperators ? string.Empty : "?")}} CreateDate => ResourceManager.GetString(nameof(CreateDate), CultureInfo){{(nullForgivingOperators ? "!" : string.Empty)}};

						/// <summary>
						/// Looks up a localized string similar to Newest.
						/// </summary>
						public{{(staticMembers ? " static" : string.Empty)}} string{{(nullForgivingOperators ? string.Empty : "?")}} CreateDateDescending => ResourceManager.GetString(nameof(CreateDateDescending), CultureInfo){{(nullForgivingOperators ? "!" : string.Empty)}};
					}
				}

				""";

		var result = generator.Generate(
			options: new GenFileOptions
			{
				LocalNamespace = "VocaDb.Web.App_GlobalResources",
				EmbeddedFilename = "VocaDb.Web.App_GlobalResources.ActivityEntrySortRuleNames",
				CustomToolNamespace = "Resources",
				ClassName = "ActivityEntrySortRuleNames",
				PublicClass = publicClass,
				NullForgivingOperators = nullForgivingOperators,
				GroupedFile = new GroupedAdditionalFile(
					mainFile: new AdditionalTextWithHash(new AdditionalTextStub("", CodeResXTestsHelpers.GetText()), Guid.NewGuid()),
					subFiles: []
				),
				StaticClass = staticClass,
				PartialClass = partial,
				StaticMembers = staticMembers,
				InnerClassName = innerClassName,
				InnerClassVisibility = innerClassVisibility,
				InnerClassInstanceName = innerClassInstanceName
			}
		);
		result.ErrorsAndWarnings.Should().BeNullOrEmpty();
		result.SourceCode.ReplaceLineEndings().Should().Be(expected.ReplaceLineEndings());
	}

	[Fact]
	public void Generate_StringBuilder_Public()
	{
		var generator = new ResourceManagerGenerator();
		Generate(generator);
		Generate(generator, nullForgivingOperators: true);
	}

	[Fact]
	public void Generate_StringBuilder_NonStatic()
	{
		var generator = new ResourceManagerGenerator();
		Generate(generator, staticClass: false);
		Generate(generator, staticClass: false, nullForgivingOperators: true);
	}

	[Fact]
	public void Generate_StringBuilder_Internal()
	{
		var generator = new ResourceManagerGenerator();
		Generate(generator, false);
		Generate(generator, false, nullForgivingOperators: true);
	}

	[Fact]
	public void Generate_StringBuilder_Partial()
	{
		var generator = new ResourceManagerGenerator();
		Generate(generator, partial: true);
		Generate(generator, partial: true, nullForgivingOperators: true);
	}

	[Fact]
	public void Generate_StringBuilder_NonStaticMembers()
	{
		var generator = new ResourceManagerGenerator();
		Generate(generator, staticMembers: false);
		Generate(generator, staticMembers: false, nullForgivingOperators: true);
	}

	[Fact]
	public void Generate_StringBuilder_Inner()
	{
		var generator = new ResourceManagerGenerator();
		GenerateInner(generator);
	}

	[Fact]
	public void Generate_StringBuilder_InnerInstance()
	{
		var generator = new ResourceManagerGenerator();
		GenerateInner(generator, innerClassInstanceName: "Resources", staticMembers: false);
	}

	[Fact]
	public void Generate_StringBuilder_NewLine()
	{
		const string expected =
			"""
			// ------------------------------------------------------------------------------
			//	<auto-generated>
			//		This code was generated by a tool.
			//
			//		Changes to this file may cause incorrect behavior and will be lost if
			//		the code is regenerated.
			//	</auto-generated>
			// ------------------------------------------------------------------------------
			#nullable enable
			namespace VocaDb.Web.App_GlobalResources;
			using System.Globalization;
			using System.Resources;

			public static class CommonMessages
			{
				private static ResourceManager? s_resourceManager;
				public static ResourceManager ResourceManager => s_resourceManager ??= new ResourceManager("VocaDb.Web.App_GlobalResources.CommonMessages", typeof(CommonMessages).Assembly);
				public static CultureInfo? CultureInfo { get; set; }

				/// <summary>
				/// Looks up a localized string similar to This entry has been deleted. It is still temporarily accessible, but won&#39;t show up in any of the listings..
				/// </summary>
				public static string? EntryDeleted => ResourceManager.GetString(nameof(EntryDeleted), CultureInfo);

				/// <summary>
				/// Looks up a localized string similar to This entry was merged to.
				/// </summary>
				public static string? EntryMergedTo => ResourceManager.GetString(nameof(EntryMergedTo), CultureInfo);

				/// <summary>
				/// Looks up a localized string similar to Draft = entry is missing crucial information. This status indicates that you&#39;re requesting additional information to be added or corrected.&lt;br /&gt;
				/// Finished = The entry has all the necessary information, but it hasn&#39;t been inspected by a trusted user yet.&lt;br /&gt;
				/// Approved = The entry has been inspected and approved by a trusted user. Approved entries can only be edited by trusted users..
				/// </summary>
				public static string? EntryStatusExplanation => ResourceManager.GetString(nameof(EntryStatusExplanation), CultureInfo);

				/// <summary>
				/// Looks up a localized string similar to This entry is locked, meaning that only moderators are allowed to edit it..
				/// </summary>
				public static string? Locked => ResourceManager.GetString(nameof(Locked), CultureInfo);

				/// <summary>
				/// Looks up a localized string similar to Choose the language for this name. &quot;Original&quot; is the name in original language that isn&#39;t English, for example Japanese. If the original language is English, do not input a name in the &quot;Original&quot; language..
				/// </summary>
				public static string? NameLanguageHelp => ResourceManager.GetString(nameof(NameLanguageHelp), CultureInfo);

				/// <summary>
				/// Looks up a localized string similar to This page revision has been hidden..
				/// </summary>
				public static string? RevisionHidden => ResourceManager.GetString(nameof(RevisionHidden), CultureInfo);
			}

			""";
		var generator = new ResourceManagerGenerator();
		var result = generator.Generate(
			options: new GenFileOptions
			{
				LocalNamespace = "VocaDb.Web.App_GlobalResources",
				EmbeddedFilename = "VocaDb.Web.App_GlobalResources.CommonMessages",
				CustomToolNamespace = null,
				ClassName = "CommonMessages",
				GroupedFile = new GroupedAdditionalFile(
					mainFile: new AdditionalTextWithHash(new AdditionalTextStub("", CodeResXTestsHelpers.GetTextWithNewline()), Guid.NewGuid()),
					subFiles: []
				),
				PublicClass = true,
				NullForgivingOperators = false,
				StaticClass = true,
				StaticMembers = true
			}
		);
		result.ErrorsAndWarnings.Should().BeNullOrEmpty();
		result.SourceCode.ReplaceLineEndings().Should().Be(expected.ReplaceLineEndings());
	}

	[Fact]
	public void Generate_StringBuilder_Name_PartialXmlWorks()
	{
		const string text =
			"""
			<?xml version="1.0" encoding="utf-8"?>
			<root>
				<data name="Works" xml:space="preserve">
					<value>Works.</value>
				</data>
			</root>
			""";

		const string expected =
			"""
			// ------------------------------------------------------------------------------
			//	<auto-generated>
			//		This code was generated by a tool.
			//
			//		Changes to this file may cause incorrect behavior and will be lost if
			//		the code is regenerated.
			//	</auto-generated>
			// ------------------------------------------------------------------------------
			#nullable enable
			namespace VocaDb.Web.App_GlobalResources;
			using System.Globalization;
			using System.Resources;

			public static class CommonMessages
			{
				private static ResourceManager? s_resourceManager;
				public static ResourceManager ResourceManager => s_resourceManager ??= new ResourceManager("VocaDb.Web.App_GlobalResources.CommonMessages", typeof(CommonMessages).Assembly);
				public static CultureInfo? CultureInfo { get; set; }

				/// <summary>
				/// Looks up a localized string similar to Works..
				/// </summary>
				public static string? Works => ResourceManager.GetString(nameof(Works), CultureInfo);
			}

			""";

		var generator = new ResourceManagerGenerator();
		var result = generator.Generate(
			options: new GenFileOptions
			{
				LocalNamespace = "VocaDb.Web.App_GlobalResources",
				EmbeddedFilename = "VocaDb.Web.App_GlobalResources.CommonMessages",
				CustomToolNamespace = null,
				GroupedFile = new GroupedAdditionalFile(
					mainFile: new AdditionalTextWithHash(new AdditionalTextStub("", text), Guid.NewGuid()),
					subFiles: []
				),
				ClassName = "CommonMessages",
				PublicClass = true,
				NullForgivingOperators = false,
				StaticClass = true,
				StaticMembers = true
			}
		);
		result.ErrorsAndWarnings.Should().BeNullOrEmpty();
		result.SourceCode.ReplaceLineEndings().Should().Be(expected.ReplaceLineEndings());
	}

	[Fact]
	public void Generate_StringBuilder_Name_DuplicateDataGivesWarning()
	{
		var generator = new ResourceManagerGenerator();
		var result = generator.Generate(
			options: new GenFileOptions
			{
				LocalNamespace = "VocaDb.Web.App_GlobalResources",
				EmbeddedFilename = "VocaDb.Web.App_GlobalResources.CommonMessages",
				GroupedFile = new GroupedAdditionalFile(
					mainFile: new AdditionalTextWithHash(new AdditionalTextStub("", CodeResXTestsHelpers.GetDaTextWithDuplicates()), Guid.NewGuid()),
					subFiles: []
				),
				CustomToolNamespace = null,
				ClassName = "CommonMessages",
				PublicClass = true,
				NullForgivingOperators = false,
				StaticClass = true
			}
		);
		var errs = result.ErrorsAndWarnings.ToList();
		errs.Should().NotBeNull();
		errs.Should().HaveCount(1);
		errs[0].Id.Should().Be(Analyser.DuplicateWarning.Id);
		errs[0].Severity.Should().Be(DiagnosticSeverity.Warning);
		errs[0].GetMessage().Should().Contain("DupKey");
		errs[0].Location.GetLineSpan().StartLinePosition.Line.Should().Be(5);
	}

	[Fact]
	public void Generate_StringBuilder_Name_MemberSameAsFileGivesWarning()
	{
		const string text =
			"""
			<?xml version="1.0" encoding="utf-8"?>
			<root>
				<data name="CommonMessages" xml:space="preserve">
					<value>Works.</value>
				</data>
			</root>
			""";

		var generator = new ResourceManagerGenerator();
		var results = generator.Generate(
			options: new GenFileOptions
			{
				LocalNamespace = "VocaDb.Web.App_GlobalResources",
				EmbeddedFilename = "VocaDb.Web.App_GlobalResources.CommonMessages",
				GroupedFile = new GroupedAdditionalFile(
					mainFile: new AdditionalTextWithHash(new AdditionalTextStub("", text), Guid.NewGuid()),
					subFiles: []
				),
				CustomToolNamespace = null,
				ClassName = "CommonMessages",
				PublicClass = true,
				NullForgivingOperators = false,
				StaticClass = true
			}
		);
		var errs = results.ErrorsAndWarnings.ToList();
		errs.Should().NotBeNull();
		errs.Should().HaveCount(1);
		errs[0].Id.Should().Be(Analyser.MemberSameAsClassWarning.Id);
		errs[0].Severity.Should().Be(DiagnosticSeverity.Warning);
		errs[0].GetMessage().Should().Contain("CommonMessages");
		errs[0].Location.GetLineSpan().StartLinePosition.Line.Should().Be(2);
	}
}
