using Aigamo.ResXGenerator.Extensions;
using Aigamo.ResXGenerator.Generators;
using Aigamo.ResXGenerator.Models;
using Aigamo.ResXGenerator.Tools;
using FluentAssertions;
using Xunit;

namespace Aigamo.ResXGenerator.Tests;

public class GlobalRegisterTests
{
	private static void Generate(
		IGlobalRegisterGenerator generator,
		bool nullForgivingOperators = false)
	{
		string expected = $$"""
							// ------------------------------------------------------------------------------
							//	<auto-generated>
							//		This code was generated by a tool.
							//
							//		Changes to this file may cause incorrect behavior and will be lost if
							//		the code is regenerated.
							//	</auto-generated>
							// ------------------------------------------------------------------------------
							{{nullForgivingOperators.InterpolateCondition("#nullable disable", "#nullable enable")}}
							using Microsoft.Extensions.DependencyInjection;
							using VocaDb.Web.App_GlobalResources;
							using VocaDb.Web.App_LocalResources;
							
							namespace ResXGenerator.Registration;
							
							public static class ResXGeneratorRegistrationExtension
							{
								public static IServiceCollection UsingResXGenerator(this IServiceCollection services)
								{
									services.UsingVocaDbWebAppGlobalResourcesResX();
									services.UsingVocaDbWebAppLocalResourcesResX();
							
									return services;
								}
							}
							""";

		var result = generator.Generate(
			options:
			[
				new GenFilesNamespace(
					"VocaDb.Web.App_GlobalResources",
					[
						new GenFileOptions
						{
							EmbeddedFilename = "VocaDb.Web.App_GlobalResources.ActivityEntrySortRuleNames",
							NullForgivingOperators = nullForgivingOperators,
						}
					]),
				new GenFilesNamespace(
					"VocaDb.Web.App_LocalResources",
					[
						new GenFileOptions
						{
							EmbeddedFilename = "VocaDb.Web.App_LocalResources.LocalViewResources",
							NullForgivingOperators = nullForgivingOperators,
						},
						new GenFileOptions
						{
							EmbeddedFilename = "VocaDb.Web.App_LocalResources.SpecificResources",
							NullForgivingOperators = nullForgivingOperators,
						}
					])
			]
		);

		result.ErrorsAndWarnings.Should().BeNullOrEmpty();
		result.SourceCode.ReplaceLineEndings().Should().Be(expected.ReplaceLineEndings());
	}

	[Fact]
	public void CanRegisterLocalClass()
	{
		var generator = new LocalizerGlobalRegisterGenerator();
		Generate(generator);
	}

	[Fact]
	public void CanRegisterLocalClassWithNullForgivingOperators()
	{
		var generator = new LocalizerGlobalRegisterGenerator();
		Generate(generator, true);
	}
}
