using Aigamo.ResXGenerator.Generators;
using Aigamo.ResXGenerator.Tools;
using FluentAssertions;
using Xunit;

namespace Aigamo.ResXGenerator.Tests;

public class HelperGeneratorTests
{
	[Fact]
	public void CanGenerateCombo()
	{
		var result = new ComboGenerator()
			.Generate(
				new CultureInfoCombo(
					files:
					[
						new AdditionalTextWithHash(new AdditionalTextStub("test.da.rex"), Guid.NewGuid()),
						new AdditionalTextWithHash(new AdditionalTextStub("test.da-dk.rex"), Guid.NewGuid())
					]
				),
				CancellationToken.None
			);
		const string expected =
			"""
			// ------------------------------------------------------------------------------
			//	<auto-generated>
			//		This code was generated by a tool.
			//
			//		Changes to this file may cause incorrect behavior and will be lost if
			//		the code is regenerated.
			//	</auto-generated>
			// ------------------------------------------------------------------------------
			#nullable enable
			namespace Aigamo.ResXGenerator;
			internal static partial class Helpers
			{
				public static string GetString_1030_6(string fallback, string da_DK, string da) => System.Globalization.CultureInfo.CurrentUICulture.LCID switch
				{
					1030 => da_DK,
					6 => da,
					_ => fallback
				};
			}

			""";
		result.ErrorsAndWarnings.Should().BeNullOrEmpty();
		result.FileName.Should().Be("Aigamo.ResXGenerator.1030_6.g.cs");
		result.SourceCode.Should().Be(expected);
	}
	[Fact]
	public void CanGenerateEmptyCombo()
	{
		var result = new ComboGenerator().Generate(new CultureInfoCombo(), CancellationToken.None);
		const string expected =
			"""
			// ------------------------------------------------------------------------------
			//	<auto-generated>
			//		This code was generated by a tool.
			//
			//		Changes to this file may cause incorrect behavior and will be lost if
			//		the code is regenerated.
			//	</auto-generated>
			// ------------------------------------------------------------------------------
			#nullable enable
			namespace Aigamo.ResXGenerator;
			internal static partial class Helpers
			{
				public static string GetString_(string fallback) => System.Globalization.CultureInfo.CurrentUICulture.LCID switch
				{
					_ => fallback
				};
			}

			""";
		result.ErrorsAndWarnings.Should().BeNullOrEmpty();
		result.FileName.Should().Be("Aigamo.ResXGenerator..g.cs");
		result.SourceCode.Should().Be(expected);
	}
}
