using Aigamo.ResXGenerator.Extensions;
using Aigamo.ResXGenerator.Generators;
using Aigamo.ResXGenerator.Models;
using Aigamo.ResXGenerator.Tools;
using FluentAssertions;
using Xunit;

namespace Aigamo.ResXGenerator.Tests;

public class LocalizerRegisterTests
{
	private static void Generate(
		ILocalRegisterGenerator generator,
		bool nullForgivingOperators = false)
	{
		string expected = $$"""
							// ------------------------------------------------------------------------------
							//	<auto-generated>
							//		This code was generated by a tool.
							//
							//		Changes to this file may cause incorrect behavior and will be lost if
							//		the code is regenerated.
							//	</auto-generated>
							// ------------------------------------------------------------------------------
							{{nullForgivingOperators.InterpolateCondition("#nullable disable", "#nullable enable")}}
							using Microsoft.Extensions.DependencyInjection;

							namespace VocaDb.Web.App_GlobalResources;

							public static class VocaDbWebAppGlobalResourcesRegistrationExtensions
							{
								public static IServiceCollection UsingVocaDbWebAppGlobalResourcesResX(this IServiceCollection services)
								{
									services.AddSingleton<IActivityEntrySortRuleNames,ActivityEntrySortRuleNames>();
									services.AddSingleton<ILocalResources,LocalResources>();
									return services;
								}
							}
							""";

		var result = generator.Generate(
			options: new GenFilesNamespace(
				"VocaDb.Web.App_GlobalResources",
				[
					new GenFileOptions
					{
						EmbeddedFilename = "VocaDb.Web.App_GlobalResources.ActivityEntrySortRuleNames",
						ClassName = "ActivityEntrySortRuleNames",
						NullForgivingOperators = nullForgivingOperators,
					},
					new GenFileOptions
					{
						EmbeddedFilename = "VocaDb.Web.App_GlobalResources.LocalResources",
						ClassName = "LocalResources",
						NullForgivingOperators = nullForgivingOperators,
					}
				]
			));

		result.ErrorsAndWarnings.Should().BeNullOrEmpty();
		result.SourceCode.ReplaceLineEndings().Should().Be(expected.ReplaceLineEndings());
	}

	[Fact]
	public void CanRegisterLocalClass()
	{
		var generator = new LocalizerRegisterGenerator();
		Generate(generator);
	}

	[Fact]
	public void CanRegisterLocalClassWithNullForgivingOperators()
	{
		var generator = new LocalizerRegisterGenerator();
		Generate(generator, true);
	}
}
